name: Publish alert-manager:test Docker Images

on: [push]

jobs:
  push_to_registry:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run build-pre.sh
        working-directory: ./src/alert-manager/build
        run: |
          chmod +x ./build-pre.sh
          ./build-pre.sh
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push alert-handler to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./src/alert-manager
          file: ./src/alert-manager/build/alert-handler.common.dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/alert-handler:test
      - name: Push cert-expiration-checker to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./src/alert-manager
          file: ./src/alert-manager/build/cert-expiration-checker.common.dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cert-expiration-checker:test
      - name: Push cluster-utilization to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./src/alert-manager
          file: ./src/alert-manager/build/cluster-utilization.common.dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cluster-utilization:test
      - name: Push job-status-change-notification to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./src/alert-manager
          file: ./src/alert-manager/build/job-status-change-notification.common.dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/job-status-change-notification:test
      - name: Push nvidia-gpu-low-perf-fixer to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./src/alert-manager
          file: ./src/alert-manager/build/nvidia-gpu-low-perf-fixer.common.dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nvidia-gpu-low-perf-fixer:test
