name: Publish postgresql:test Docker Image

on: [push]

jobs:
  push_to_registry:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push postgresql to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./src/postgresql
          file: ./src/postgresql/build/postgresql.k8s.dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/postgresql:test
      - name: Push postgresql-init-client to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./src/postgresql
          file: ./src/postgresql/build/postgresql-init-client.k8s.dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/postgresql-init-client:test
